# 1. Các phép toán trên vector và ma trận.

### 1.1 Length of a vector



In [1]:
import numpy as np

def compute_vector_length(vector):
    # *********** Your code here ***********
    v = np.array(vector)
    len_of_vector = np.linalg.norm(v)

    return len_of_vector

In [2]:
v = [1, 2, 3]
compute_vector_length(v)

3.7416573867739413

### 1.2 Dot product

In [3]:
def compute_dot_product(vector1, vector2):
    # *********** Your code here ***********
    v1 = np.array(vector1)
    v2 = np.array(vector2)
    result = np.dot(v1, v2)

    return result

In [4]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]
compute_dot_product(v1, v2)

32

### 1.3 Multiplying a vector by a matrix

In [5]:
def matrix_multi_vector(matrix, vector):
    # *********** Your code here ***********
    A = np.array(matrix)
    v = np.array(vector)
    result = np.dot(A, v)

    return result

In [6]:
A = [[1, 2], [3, 4], [5, 6]]
v = [7, 8]
matrix_multi_vector(A, v)

array([23, 53, 83])

### 1.4 Multiplying a matrix by a matrix

In [7]:
import numpy as np

def matrix_multi_matrix(matrix1, matrix2):
  A = np.array(matrix1)
  B = np.array(matrix2)
  result = np.matmul(A, B)

  return result

In [8]:
A = [[1, 2], [3, 4], [5, 6]]
B = [[7, 8, 9], [10, 11, 12]]
matrix_multi_matrix(A, B)

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

### 1.5 Matrix inverse

In [9]:
import numpy as np

def inverse_matrix(matrix):
  A = np.array(matrix)
  det = np.linalg.det(A)
  if det == 0:
    return None
  else:
    result = np.linalg.inv(A)
  return result

In [10]:
A = [[-2, 6], [8, -4]]
inverse_matrix(A)

array([[0.1 , 0.15],
       [0.2 , 0.05]])

## 2. Eigenvector và eigenvalues:

In [11]:
import numpy as np

def compute_eigenvalues_eigenvectors(matrix):
  A = np.array(matrix)
  eigenvalues = np.linalg.eigvals(A)
  eigenvectors = np.linalg.eig(A)

  return eigenvalues, eigenvectors

In [12]:
A = [[0.9, 0.2], [0.1, 0.8]]
compute_eigenvalues_eigenvectors(A)

(array([1. , 0.7]),
 EigResult(eigenvalues=array([1. , 0.7]), eigenvectors=array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]])))

## 3. Cosine Similarity:

In [13]:
def compute_cosine(v1, v2):
    # *********** Your code here ***********
    x = np.array(v1)
    y = np.array(v2)
    cos_sim = np.dot(x, y) / np.dot(np.linalg.norm(x), np.linalg.norm(y))

    return cos_sim

In [14]:
x = [1, 2, 3, 4]
y = [1, 0, 1, 0]
compute_cosine(x, y)

0.5163977794943222