In [ ]:
# Câu 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9
import numpy as np

arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Câu 2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True

arr = np.full((3,3), fill_value=True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Câu 3: Kết quả của đoạn code sau đây:

import numpy as np

arr = np.arange(0,10)
print(arr[arr%2==1])

[1 3 5 7 9]


In [ ]:
# Câu 4: Kết quả của đoạn code sau đây:

arr = np.arange(0,10)
arr[arr%2==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Câu 5: Kết quả của đoạn code sau đây:

arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# Câu 6: Kết quả của đoạn code sau đây:

arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# Câu 7: Kết quả của đoạn code sau đây:

arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
# Câu 8: Kết quả của đoạn code sau đây:

arr=np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
# Câu 9: Kết quả của đoạn code sau đây:

a = np.array([2, 6, 1, 9, 10, 3, 27])
idx = np.where((a>=5)&(a<=10))
print(a[idx])

[ 6  9 10]


In [ ]:
# Câu 10: Kết quả của đoạn code sau đây:

def max(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np.vectorize(max, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [ ]:
# Câu 11: Kết quả của đoạn code sau đây:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

print(np.where(a<b, b, a))

[6 7 9 8 9 7 5]


## Bài tập 2: Xử lý ảnh
Các câu hỏi phần này giải quyết bài toán chuyển ảnh màu về ảnh xám.
Ảnh sẽ được biểu diễn bởi tập các điểm ảnh (Pixel) có giá trị từ 0 đến 255. Ảnh màu sẽ được biểu
diễn thành ma trận có kích thước (Height, Width, Channel); trong đó số Channel là 3 tương ứng là giá
trị biểu diễn cho các kênh màu R-Red, G-Green, B-Blue. Ảnh xám sẽ được biểu diễn thành ma trận
có kích thước (Height, Width). Vì vậy, để chuyển ảnh màu thành ảnh xám, chúng ta sẽ tổng hợp từ 3
kênh màu RGB thành 1 giá trị duy nhất trong khoảng 0 đến 255. Có 3 phương pháp chính để tính giá
trị chuyển đổi:
* Lightness: Tính giá trị trung bình của giá trị lớn nhất và nhỏ nhất cho các kênh màu: (max(R,G,B)
+ min(R,G,B))/2
* Average: Tính giá trị trung bình của 3 kênh màu: (R+G+B)/3
* Luminosity: Nhân hệ số tương ứng của 3 kênh màu như sau: 0.21*R + 0.72*G + 0.07*B

In [ ]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 63.7MB/s]


In [ ]:
# Câu 12: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào
# phương pháp Lightness:

import matplotlib.image as mpimg

img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (img.max(axis=-1) + img.min(axis=-1))/2
gray_img_01[0, 0]

102.5

In [ ]:
# Câu 13: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào
# phương pháp Average:

gray_img_02 = img.mean(axis=-1)
gray_img_02[0, 0]

107.66666666666667

In [ ]:
# Câu 14: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào
# phương pháp Luminosity:

gray_img_03 = 0.21*img[:,:,0] + 0.72*img[:,:,1] + 0.07*img[:,:,2]
gray_img_03[0, 0]

126.22999999999999

## Bài tập 3: Phân tích dữ liệu dạng bảng
Các câu hỏi phần này ứng dụng numpy trong phân tích dữ liệu dạng bảng, được mô tả gồm các cột và
một số hàng như sau:

|    |   TV  |   Radio |   Newspaper |   Sales |
|----|-------|---------|-------------|---------|
|  0 | 230.1 |    37.8 |        69.2 |    22.1 |
|  1 |  44.5 |    39.3 |        45.1 |    10.4 |
|  2 |  17.2 |    45.9 |        69.3 |    12.0 |
|  3 | 151.5 |    41.3 |        58.5 |    16.5 |
|  4 | 180.8 |    10.8 |        58.4 |    17.9 |

Dựa vào đoạn code sau để tải về dữ liệu và thực hiện các đoạn code cho các các câu hỏi sau để chọn
đáp án đúng:

In [ ]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.9MB/s]


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy

In [ ]:
# Câu 15: Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales:

sales_column = df['Sales']
max_value = sales_column.max()
print(max_value)
max_value = sales_column.argmax()
print(max_value)

27.0
175


In [ ]:
# Câu 16: Giá trị trung bình của cột TV là:

tv_column = df['TV']
tv_column_mean = tv_column.mean()
print(tv_column_mean)

147.0425


In [ ]:
# Câu 17: Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là:

sales_count = (sales_column >= 20).sum()
print(sales_count)

40


In [ ]:
# Câu 18: Tính giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng
# trên cột Sales lớn hơn hoặc bằng 15:

radio_column = df['Radio']
filtered_df = df[df['Sales'] >= 15]
mean_radio = filtered_df['Radio'].mean()
print(mean_radio)

26.22293577981651


In [ ]:
# Câu 19: Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn
# giá trị trung bình của cột Newspaper:

filtered_df_news = df[df['Newspaper'] >= df['Newspaper'].mean()]
sales_sum = filtered_df_news['Sales'].sum()
print(sales_sum)

1405.1


In [ ]:
# Câu 20: Gọi giá trị trung bình của cột Sales là A. Tạo ra mảng mới scores chứa các
# giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới
# là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]

A = df['Sales'].mean()
scores = []

for value in df['Sales']:
    if value > A:
        scores.append('Good')
    elif value < A:
        scores.append('Bad')
    else:
        scores.append('Average')

print(scores[7:10])


['Bad', 'Bad', 'Good']


In [ ]:
# Câu 21: Gọi giá trị trên cột Sales gần nhất với giá trị trung bình cũng chính cột
# Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu
# giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là
# Average. Sau đó in ra kết quả scores[7:10]

closet_value = df['Sales'].iloc[(df['Sales'] - A).abs().argmin()]
scores = []

for value in df['Sales']:
    if value > closet_value:
        scores.append('Good')
    elif value < closet_value:
        scores.append('Bad')
    else:
        scores.append('Average')
print(scores[7:10])

['Bad', 'Bad', 'Good']
